FROM node:21

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY src ./src
COPY tsconfig.json ./
# COPY prisma ./prisma

# RUN npx prisma generate

# RUN npm run build
RUN npx tsc

EXPOSE 5000

CMD ["npm","start"]